profile:
bot_token: #TOKEN


gpt:
  url:
  model:
  token:

db:
  name:
  port:
  host:
  password:
  user:

logging:
    app_name: RAG-bot
    graylog:
      enabled: false
      udp: false
    console:
      enabled: true
    root_level: INFO
    levels:
      httpx: WARN
      openai: WARN
      uvicorn.access: WARN
