version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_rel
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rel_db
    ports:
      - "5437:5432"